/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ReviewAnalyzer {
  constructor(modelBytes: Array<number>, tokenizerBytes: Array<number>)
  /**
   * Analyzes a diff in chunks.
   *
   * # Safety
   *
   * This method is marked unsafe because it is an async N-API method that takes `&mut self`.
   * The caller must ensure that this method is not called concurrently on the same instance
   * from the JavaScript thread, as `napi-rs` cannot statically guarantee mutable access across
   * the async bridge.
   */
  analyzeDiffChunked(diff: string, context: string, maxTokensPerChunk: number): Promise<string>
}
